"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.VALIDATE_TRANSLATED_FILE = exports.VALIDATE_STRINGS = exports.VALUE_CHANGED = void 0;
var VALUE_CHANGED = "VALUE_CHANGED";
exports.VALUE_CHANGED = VALUE_CHANGED;
var VALIDATE_STRINGS = "VALIDATE_STRINGS";
exports.VALIDATE_STRINGS = VALIDATE_STRINGS;
var VALIDATE_TRANSLATED_FILE = "VALIDATE_TRANSLATED_FILE";
exports.VALIDATE_TRANSLATED_FILE = VALIDATE_TRANSLATED_FILE;